/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.academia.Views;

import co.academia.Beans.Asistencia;
import co.academia.DAO.DAO_asistencia;
import co.academia.DAO.DAO_estudiante;
import co.academia.Table.Tb_asistencia;
import java.sql.Date;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;

/**
 *
 * @author ROBERT
 */
public class GUI_registrarAsistencia extends javax.swing.JInternalFrame {

    private Tb_asistencia logica;
    DAO_estudiante daoE;

    public GUI_registrarAsistencia() {
        initComponents();

        try {
            daoE = new DAO_estudiante();
            //re = new RenderElements();

            this.logica = new Tb_asistencia(daoE.read_estudiante());

            tb_registrarA.setModel(logica.mostrarRegistros(false));
            //re.addChechBox(4, tb_registrarA);

            //le indicamos que cundo se cierre solo se oculte pero el program no se cierre;
            //setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            
            //addChechBox(5, tb_registrarA);
            addButton(5, tb_registrarA);

        } catch (SQLException e) {
        }

        //obtenemos la fecha actual
        LocalDate todaysDate = LocalDate.now();
        txt_fecha.setText(String.valueOf(todaysDate));
        txt_fecha.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_fecha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_registrarA = new javax.swing.JTable();
        checkb_marcar = new javax.swing.JCheckBox();
        btn_guardarAsistencia = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setTitle("Asistencia");
        setFrameIcon(new javax.swing.ImageIcon("D:\\academia\\ControlNotasAsistencia\\src\\main\\java\\icon\\calendar_25.png")); // NOI18N

        txt_fecha.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt_fecha.setForeground(new java.awt.Color(0, 0, 0));
        txt_fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fecha.setToolTipText("FECHA");
        txt_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fechaActionPerformed(evt);
            }
        });

        tb_registrarA = new javax.swing.JTable(){

            public boolean isCellEditable(int rowIndex, int colIndex){
                return true;
            }
        };
        tb_registrarA.setAutoCreateRowSorter(true);
        tb_registrarA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_registrarA.setColumnSelectionAllowed(true);
        tb_registrarA.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tb_registrarA.setRowHeight(30);
        tb_registrarA.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(tb_registrarA);

        checkb_marcar.setText("Seleccionar Todos");
        checkb_marcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkb_marcarActionPerformed(evt);
            }
        });

        btn_guardarAsistencia.setText("GUARDAR ASISTENCIA");
        btn_guardarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarAsistenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkb_marcar)
                        .addGap(54, 54, 54)
                        .addComponent(btn_guardarAsistencia))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkb_marcar)
                    .addComponent(btn_guardarAsistencia))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fechaActionPerformed

    private void checkb_marcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkb_marcarActionPerformed
        //String sel = String.valueOf(rbuton_asistencia.isSelected());
        if (checkb_marcar.isSelected()) {

            checkb_marcar.setText("Deselcionar todos");
            tb_registrarA.setModel(logica.mostrarRegistros(true));
            //tb_registrarA.setModel(logica.selectAllCheckBox());
        } else {
            //select false
            checkb_marcar.setText("Seleccionar todos");
            tb_registrarA.setModel(logica.mostrarRegistros(false));
        }
    }//GEN-LAST:event_checkb_marcarActionPerformed

    private void btn_guardarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarAsistenciaActionPerformed
        DAO_asistencia daoA;

        int row = tb_registrarA.getRowCount();
        Asistencia asistencia;
        String fecha = txt_fecha.getText();

        for (int i = 0; i < row; i++) {
            boolean ban = Boolean.parseBoolean(String.valueOf(tb_registrarA.getValueAt(i, 5)));
            if (ban != false) {
                daoA = new DAO_asistencia();
                asistencia = new Asistencia();

                asistencia.setId_estudiante(String.valueOf(tb_registrarA.getValueAt(i, 1)));
                asistencia.setFecha(Date.valueOf(fecha));
                asistencia.setId_categoria_asistencia(1);
                daoA.Asistencia_Insert(asistencia);

            } else {

                daoA = new DAO_asistencia();
                asistencia = new Asistencia();

                asistencia.setId_estudiante(String.valueOf(tb_registrarA.getValueAt(i, 1)));
                asistencia.setFecha(Date.valueOf(fecha));
                asistencia.setId_categoria_asistencia(2);
                daoA.Asistencia_Insert(asistencia);

            }

        }
        JOptionPane.showMessageDialog(null, "GUARDAR ASISTENCIA");
    }//GEN-LAST:event_btn_guardarAsistenciaActionPerformed

    public void addChechBox(int column, JTable table) {
        TableColumn tc = table.getColumnModel().getColumn(column);
        tc.setCellEditor(table.getDefaultEditor(Boolean.class));
        tc.setCellRenderer(table.getDefaultRenderer(Boolean.class));
    }

    public boolean IsSelected(int row, int column, JTable table) {
        return (boolean) table.getValueAt(row, column);
    }

    public void addButton(int column, JTable table) {
        TableColumn tc = table.getColumnModel().getColumn(column);
        tc.setCellEditor(table.getDefaultEditor(Boolean.class));
        tc.setCellRenderer(table.getDefaultRenderer(Boolean.class));
    }
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardarAsistencia;
    private javax.swing.JCheckBox checkb_marcar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_registrarA;
    private javax.swing.JTextField txt_fecha;
    // End of variables declaration//GEN-END:variables
}
