/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.academia.Views;

import co.academia.Beans.Notas;
import co.academia.Beans.Parcial;
import co.academia.DAO.DAO_estudiante;
import co.academia.DAO.DAO_notas;
import co.academia.DAO.DAO_parcial;
import co.academia.Table.Tb_subir_notas;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ROBERT
 */
public class registrar_notas extends javax.swing.JFrame {

    Tb_subir_notas logica;
    DAO_estudiante daoE;
    DAO_parcial daoParcial;
    DAO_notas daoNotas;

    public registrar_notas() throws SQLException {
        initComponents();

        daoE = new DAO_estudiante();
        logica = new Tb_subir_notas(daoE.read_estudiante());
        tb_subir_notas.setModel(logica.mostrarRegistros());

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_subir_notas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txt_fecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        cbx_curso = new javax.swing.JComboBox<>();
        btn_save = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        menu_bar = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        btn_estudiantes = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        asistencia_diaria_btn = new javax.swing.JMenuItem();
        asistencia_mensual_btn = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setMaximumSize(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("REGISTRO DE NOTAS");

        tb_subir_notas = new javax.swing.JTable(){

            public boolean isCellEditable(int rowIndex, int colIndex){
                return true;
            }
        };
        tb_subir_notas.setAutoCreateRowSorter(true);
        tb_subir_notas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_subir_notas.setColumnSelectionAllowed(true);
        tb_subir_notas.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tb_subir_notas.setRowHeight(30);
        tb_subir_notas.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(tb_subir_notas);

        jPanel1.setBackground(new java.awt.Color(215, 215, 215));

        txt_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fechaActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("FECHA:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NOMBRE ");

        cbx_curso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_save.setText("GUARDAR");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CURSO:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_curso, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(cbx_curso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addGap(28, 28, 28)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        menu_bar.setBackground(new java.awt.Color(255, 102, 51));

        jMenu6.setBackground(new java.awt.Color(255, 255, 255));
        jMenu6.setForeground(new java.awt.Color(0, 0, 0));
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agenda2.png"))); // NOI18N
        jMenu6.setText("HOME");
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("HOME");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        menu_bar.add(jMenu6);

        btn_estudiantes.setBackground(new java.awt.Color(255, 255, 255));
        btn_estudiantes.setForeground(new java.awt.Color(0, 0, 0));
        btn_estudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agenda2.png"))); // NOI18N
        btn_estudiantes.setText("ESTUDIANTES");
        btn_estudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_estudiantesActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Registrar Estudiante");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        btn_estudiantes.add(jMenuItem1);

        menu_bar.add(btn_estudiantes);

        jMenu4.setBackground(new java.awt.Color(255, 255, 255));
        jMenu4.setForeground(new java.awt.Color(0, 0, 0));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agenda2.png"))); // NOI18N
        jMenu4.setText("NOTAS");

        jMenuItem4.setText("INGRESAR NOTAS");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenu2.setText("VIZUALIZAR NOTAS");

        jMenuItem5.setText("NOTAS POR PARCIAL");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("NOTAS GENERALES");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenu4.add(jMenu2);

        menu_bar.add(jMenu4);

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agenda2.png"))); // NOI18N
        jMenu1.setText("ASISTENCIA");

        jMenuItem3.setText("REGISTRAR ASISTENCIA");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenu3.setText("VIZUALIZAR ASISTENCIA");

        asistencia_diaria_btn.setText("ASISTENCIA DIARIA");
        asistencia_diaria_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asistencia_diaria_btnActionPerformed(evt);
            }
        });
        jMenu3.add(asistencia_diaria_btn);

        asistencia_mensual_btn.setText("ASISTENCIA MENSUAL");
        asistencia_mensual_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asistencia_mensual_btnActionPerformed(evt);
            }
        });
        jMenu3.add(asistencia_mensual_btn);

        jMenu1.add(jMenu3);

        menu_bar.add(jMenu1);

        jMenu5.setBackground(new java.awt.Color(255, 255, 255));
        jMenu5.setForeground(new java.awt.Color(0, 0, 0));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agenda2.png"))); // NOI18N
        jMenu5.setText("PAGOS");

        jMenuItem7.setText("REGISTRAR PAGOS");
        jMenu5.add(jMenuItem7);

        jMenuItem8.setText("REVISAR PAGOS");
        jMenu5.add(jMenuItem8);

        menu_bar.add(jMenu5);

        setJMenuBar(menu_bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        home h = new home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed

    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        V_estudiantes V;
        try {
            V = new V_estudiantes();
            V.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btn_estudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_estudiantesActionPerformed

    }//GEN-LAST:event_btn_estudiantesActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        registrar_notas rn;
        try {
            rn = new registrar_notas();
            rn.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(V_estudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        V_notas_parcial vnp = new V_notas_parcial();
        vnp.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        V_notas_general vng = new V_notas_general();
        vng.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        registrar_asistencia ra;
        try {
            ra = new registrar_asistencia();
            ra.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(V_estudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void asistencia_diaria_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asistencia_diaria_btnActionPerformed
        v_asistencia_diaria ad = new v_asistencia_diaria();
        ad.setVisible(true);
    }//GEN-LAST:event_asistencia_diaria_btnActionPerformed

    private void asistencia_mensual_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asistencia_mensual_btnActionPerformed
        V_asistencia_mensual am = new V_asistencia_mensual();
        am.setVisible(true);
    }//GEN-LAST:event_asistencia_mensual_btnActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed

        READ_TABLE();
        JOptionPane.showMessageDialog(null, "Notas Registradas con exito. [ok]");


    }//GEN-LAST:event_btn_saveActionPerformed

    private void txt_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fechaActionPerformed

    }//GEN-LAST:event_txt_fechaActionPerformed

    private void READ_TABLE() {
        if (VALIDATE_TABLE() != false && VALIDATE_CAMPOS()!= false) {
            //obtenemos daots:
            int id_parcial = 1;
            //SE BUSCA EL CODIGO DEL CURSO A PARTIR DEL NOMBRE
            //... por defecto utilizaremos el nro 1.
            String curso = String.valueOf(cbx_curso.getSelectedItem());
            int id_curso = 1;
            int num_preguntasM = 0;
            int num_preguntasB = 0;
            float total = 0.0f;

            List<Notas> lista = new ArrayList<>();
            Notas notas = new Notas();
            int row = tb_subir_notas.getRowCount();
            daoNotas = new DAO_notas();
            for (int i = 0; i < row; i++) {
                
                Float puntaje = 0.0f;
                try {
                    puntaje = Float.parseFloat(String.valueOf(tb_subir_notas.getValueAt(i, 3)));
                    total += puntaje;
                    String dni = String.valueOf(tb_subir_notas.getValueAt(i, 1));
                    notas = new Notas();
                    notas.setNum_preguntasM(num_preguntasM);
                    notas.setNum_preguntasB(num_preguntasB);
                    notas.setId_parcial(id_parcial);
                    notas.setId_curso(id_curso);
                    notas.setDni(dni);
                    notas.setPuntaje(puntaje);
                    lista.add(notas);
                    System.out.println("PASO 1");
                } catch (NumberFormatException nx) {
                    puntaje = 0.0f;
                }

            }
            REGISTRAR_PARCIAL(id_parcial, total);
            System.out.println("Parcial insertado con exito [ok]");
            daoNotas.INSERT_NOTAS_PARCIAL(lista);
            System.out.println("Parcial insertado con exito [ok]");
        } else {
            JOptionPane.showMessageDialog(null, "[ERROR] Campos Vacios.");
        }

    }

    private void REGISTRAR_PARCIAL(int id_parcial, float total) {

        //obtenemos el id del parcial: incremental
        String nombre_parcial = txt_name.getText();
        String fecha = txt_fecha.getText();

        Parcial parcial = new Parcial();
        parcial.setId_parcial(id_parcial);
        parcial.setFecha(Date.valueOf(fecha));
        parcial.setNombre(nombre_parcial);
        parcial.setTotal(total);
        parcial.setEstado(1);

        daoParcial = new DAO_parcial();
        daoParcial.INSERT_PARCIAL(parcial);
    }

    public boolean VALIDATE_TABLE() {
        //validar si hay por lo menos 1 nota registrada.
        boolean band = false;
        int row = tb_subir_notas.getRowCount();

        for (int i = 0; i < row; i++) {
            if (tb_subir_notas.getValueAt(i, 3) != null) {
                return true;
            }
        }

        return band;
    }
    
    public boolean VALIDATE_CAMPOS(){
        return txt_fecha.getText() != null && txt_name.getText() !=null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(registrar_notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(registrar_notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(registrar_notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(registrar_notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new registrar_notas().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(registrar_notas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem asistencia_diaria_btn;
    private javax.swing.JMenuItem asistencia_mensual_btn;
    private javax.swing.JMenu btn_estudiantes;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cbx_curso;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menu_bar;
    private javax.swing.JTable tb_subir_notas;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
